### ISSUE TITLE
[BUG] Leaks - ft_strdup & ft_substr & malloc

### ISSUE THREAD

**Issue by LuyNagda** [42-Lyon-Projects/minishell-revamp#13]
### already_exist

- [x] I've checked to see if the bug has already been reported

### Github Branch Name

12-merge-new-parsing-with-pipex

### Discord username

luynagda

### What Happened ?

Leaks due to passing a malloc'd without ever freeing it.

### Steps to reproduce the bug / problem.

make with valgrind, run minishell
run commands:
cat|cat|ls
exit

### What was supposed to happen ?

No leaks.

### Screenshot or vidéo

<img width="796" alt="image" src="https://github.com/42-Lyon-Projects/minishell-revamp/assets/20789141/8af43a06-4ac8-4065-886e-a95a56d3c792">

As you can see in the below screenshot, using ft_substr directly in a function is wrong (line 100 and 107):
<img width="535" alt="image" src="https://github.com/42-Lyon-Projects/minishell-revamp/assets/20789141/b99af15c-c292-4782-9984-a24138a6f923">

Likewise, same issue here:
<img width="586" alt="image" src="https://github.com/42-Lyon-Projects/minishell-revamp/assets/20789141/2fa5a2b8-a713-4c42-b64a-5d35311791d4">

**Comment by vSKAH** [comment]
Okay, i will try this and fix it in the branch associated on issue

**Comment by vSKAH** [comment]
I have pushed patch in 13-bug-leaks-ft_strdup-ft_substr-malloc.

This Patch contains :

:bug: Sended line are now correctly free
:bug: Token value are now correctly free

**Comment by vSKAH** [comment]
There's still a leak on the commands, I'll look into it and try to fix it soon enough.

**Comment by vSKAH** [comment]
merged
