### ISSUE TITLE
[BUG] Leak

### ISSUE THREAD

**Issue by LuyNagda** [42-Lyon-Projects/minishell-revamp#47]
<img width="711" alt="image" src="https://github.com/42-Lyon-Projects/minishell-revamp/assets/20789141/c804398b-66b1-4c73-ae1e-06bcb7b788e8">

root@6691fa2149fc:/project# valgrind --leak-check=full --suppressions=supp.supp --show-leak-kinds=all ./minishell
==2256== Memcheck, a memory error detector
==2256== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2256== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==2256== Command: ./minishell
==2256== 
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ^C
➜ minishell : ls
Makefile  build  dependencies  includes  minishell  sources  supp.supp
==2256== Invalid free() / delete / delete[] / realloc()
==2256==    at 0x4867AD0: free (in /usr/libexec/valgrind/vgpreload_memcheck-arm64-linux.so)
==2256==    by 0x10B42F: env_map_replace (env_setter.c:75)
==2256==    by 0x10C193: exec_cmd (exec_pipex.c:118)
==2256==    by 0x10BAC7: ft_dispatch_command (exec_dispatcher.c:77)
==2256==    by 0x109317: tokenize_and_run (main.c:57)
==2256==    by 0x1093F3: ft_shell_loop (main.c:85)
==2256==    by 0x1094B7: main (main.c:105)
==2256==  Address 0x1128e0 is in a r-x mapped file /project/minishell segment
==2256== 
➜ minishell : ^C

**Comment by LuyNagda** [comment]
<img width="645" alt="image" src="https://github.com/42-Lyon-Projects/minishell-revamp/assets/20789141/ef922711-b397-43ed-91b4-7e3bf846ecc6">

I dont know if this is because of the docker env or this really happens, can you please check and let me know

**Comment by vSKAH** [comment]
I don't know what you've done but I don't think it's me, there wasn't this problem before.

**Comment by vSKAH** [comment]
@LuyNagda @luyfornice

**Comment by vSKAH** [comment]
I told you I was going to take care of the signals, now that you've done them I've no idea where the problem lies.

**Comment by vSKAH** [comment]
Invalid free is fixed in commit c5569afc4be02d3a75f1b06921a6a3a1b92d733d
