### ISSUE TITLE
[BUG] treating tabs as spaces

### ISSUE THREAD

**Issue by LuyNagda** [42-Lyon-Projects/minishell-revamp#48]
<img width="531" alt="image" src="https://github.com/42-Lyon-Projects/minishell-revamp/assets/20789141/61adf845-e31f-4ad5-bf8c-7a39b7769ae5">

when I use tab in quotes with something, a space is printed instead of tab.

**Comment by vSKAH** [comment]
yes it's normal tab is treated like a space to avoid errors

**Comment by LuyNagda** [comment]
nope. check in bash.

**Comment by vSKAH** [comment]
ok, this is fixed in commit 58e44b002d13a69bff6b05d39e4a521a9fd2555e but be careful, it may bring bugs, so thorough testing is required.
