### ISSUE TITLE
[ENHANCEMENT] Make sure all errors are printed on stderr

### ISSUE THREAD

**Issue by LuyNagda** [42-Lyon-Projects/minishell-revamp#65]
<img width="241" alt="image" src="https://github.com/42-Lyon-Projects/minishell-revamp/assets/20789141/63a2e1ad-9285-4847-939e-6bc85b9d9795">

**Comment by LuyNagda** [comment]
7058b60eef6d25347fae28ab6d760aca121d57de
Fixed in the above commit, could you just pls verify this?

**Comment by vSKAH** [comment]
looks good
