### ISSUE TITLE
[BUG] Issue with parsing

### ISSUE THREAD

**Issue by LuyNagda** [42-Lyon-Projects/minishell-revamp#66]
Parsing has issue. 
<img width="407" alt="image" src="https://github.com/42-Lyon-Projects/minishell-revamp/assets/20789141/727b7b47-3aac-4324-87ff-272748fb33f1">

**Comment by vSKAH** [comment]
Fixed in #65dd2764170204aaeca5bf3806da732c8d7d0f95
Please check the commit information, it can cause several bugs/errors/crashes.
